name: Build and Release APK
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Fix line endings
        run: sed -i 's/\r$//' gradlew && chmod +x gradlew
      - name: Build APK
        run: ./gradlew clean build assembleDebug -x lint
      - name: Upload APK
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
          tag_name: release-$(date +'%Y-%m-%d_%H-%M-%S')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
